services:
  node-app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
